# Generated by Django 4.2 on 2023-04-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_item_market_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketcommunication',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
