# Generated by Django 4.2 on 2023-04-23 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_marketcommunication_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketcommunication',
            name='value',
        ),
    ]
