# Generated by Django 4.2 on 2023-04-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_remove_marketcommunication_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketcommunication',
            name='value',
            field=models.CharField(blank=True, choices=[('Im interested', 'Im Interested'), ('Im not interested anymore', 'Im not interested anymore')], max_length=25),
        ),
    ]
