# Generated by Django 4.2 on 2023-04-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_marketcommunication_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='no se especifica', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.CharField(default='no se especifica', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(default='indefinida', max_length=40),
        ),
        migrations.AlterField(
            model_name='marketcommunication',
            name='value',
            field=models.CharField(blank=True, choices=[('Im interested', 'Im Interested'), ('Im not interested', 'Im not interested')], max_length=25),
        ),
    ]
