# Generated by Django 4.2 on 2023-04-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_item_category_item_condition_item_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketcommunication',
            name='email',
            field=models.EmailField(default='enter your email', max_length=80),
        ),
        migrations.AddField(
            model_name='marketcommunication',
            name='name',
            field=models.CharField(default='enter your name', max_length=50),
        ),
    ]
