# Generated by Django 4.2 on 2023-04-18 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_rename_last_active_userstatus_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='is_active',
            field=models.BooleanField(),
        ),
    ]
