# Generated by Django 4.2 on 2023-04-18 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_alter_userstatus_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStatus',
        ),
    ]
